import random
import time

# Color codes
class Colors: 
    RESET = "\033[0m"
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    PURPLE = "\033[95m"
    CYAN = "\033[96m"

# Constants
DIGITS = 4
SEPARATOR = "-" * 50

# Prints the introductory text for the Bulls & Cows game.

def print_intro() -> None:
    """
    Prints the introductory text for the Bulls & Cows game.
    """
    print("Hi there!")
    print(f"{Colors.BLUE}{SEPARATOR}{Colors.RESET}")
    print(f"I've generated a random {DIGITS}-digit number for you.")
    print(f"Let's play a bulls and cows game.")
    print(f"{Colors.BLUE}{SEPARATOR}{Colors.RESET}")
    print()  # empty line for breathing space

# Game logic 

def generate_secret_number() -> str:
    """
    Generates a 4-digit secret number with unique digits and no leading zero.

    Returns:
        str: The generated secret number.
    """
    first_digit = random.choice("123456789")
    three_digits = random.sample("0123456789".replace(first_digit,""), 3)
    
    secret = first_digit + "".join(three_digits)
    return secret

# Comparison with the secret number

def evaluate_guess(secret: str, guess: str) -> tuple[int, int]:
    """
    Compares the player's guess with the secret number and counts bulls and cows.

    Args:
        secret (str): The secret number generated by the game.
        guess (str): The player's guess.

    Returns:
        tuple[int, int]: Number of bulls and cows.
    """
    bulls = 0
    cows = 0
    
    for s, g in zip(secret, guess):
        if s == g:
            bulls += 1
        elif g in secret:
            cows += 1

    return bulls, cows

# Input validation

def is_valid_guess(guess: str) -> bool:
    """
    Checks whether the player's guess is valid.

    Args:
        guess (str): The player's input.

    Returns:
        bool: True if the guess is valid, otherwise False.
    """
    if len(guess) != DIGITS:
        return False
    
    if not guess.isdigit():
        return False
    
    if len(set(guess)) != DIGITS:
        return False
    
    if guess[0] == "0":
        return False
    return True

# Returns the correct singular/plural form based on the count.

def format_word(count: int, singular: str, plural: str) -> str:
    """
    Returns the correct singular or plural form based on the count.

    Args:
        count (int): The number determining the form.
        singular (str): The singular form of the word.
        plural (str): The plural form of the word.

    Returns:
        str: The correct word form.
    """

    return singular if count == 1 else plural

# Main game loop for Bulls & Cows.

def play_game() -> None:
    """
    Runs the main game loop for Bulls & Cows.

    Handles user input, validates guesses, evaluates results, and tracks attempts and time.
    """

    print_intro()
    secret = generate_secret_number()
    attempts = 0
    start_time = time.time()

    while True:
        guess = input(f"{Colors.CYAN}Enter a number: {Colors.RESET}")

        if not is_valid_guess(guess):
            print(f"{Colors.RED}Invalid input. Enter {DIGITS} unique digits (no leading zero).{Colors.RESET}")
            continue
        
        attempts += 1

        bulls, cows = evaluate_guess(secret, guess)
        bull_word = format_word(bulls, "bull", "bulls")
        cow_word = format_word(cows, "cow", "cows")
        print(f"{Colors.GREEN}{bulls} {bull_word}{Colors.RESET}, {Colors.YELLOW}{cows} {cow_word}{Colors.RESET}")
        print()  # improves readability between guesses

        if bulls == DIGITS:
            end_time = time.time()
            duration = end_time - start_time
            print(f"{Colors.GREEN}Correct, you've guessed the right number!{Colors.RESET}")
            print(f"{Colors.BLUE}{SEPARATOR}{Colors.RESET}")
            print(f"You guessed the number in {attempts} attempts.")
            print(f"You finished the game in {duration:.1f} seconds.")
            print(f"{Colors.BLUE}{SEPARATOR}{Colors.RESET}")
            print()
            print(f"{Colors.PURPLE}That's amazing!{Colors.RESET}")
            break

def main():
    """
    Entry point of the program. Starts the Bulls & Cows game.
    """
    while True:
        play_game()
        again = input(f"Do you want to play again? (y/n): ").strip().lower()
    
        if again == "y":
            print()
            continue
        elif again == "n":
            print(f"{Colors.PURPLE}Thanks for playing. Goodbye!{Colors.RESET}")
            break
        else:
            print(f"{Colors.RED}Invalid choice. Exiting the game.{Colors.RESET}")
            break

if __name__ == "__main__":
    main()


